services:
  # Banco de dados PostgreSQL
  db:
    container_name: cintegre_db
    image: bitnami/postgresql:latest
    ports:
      - "${DB_PORT}:5432"
    environment:
      - POSTGRESQL_USERNAME=${POSTGRESQL_USERNAME}
      - POSTGRESQL_PASSWORD=${POSTGRESQL_PASSWORD}
      - POSTGRESQL_DATABASE=${POSTGRESQL_DATABASE}
    volumes:
      - postgresql_data:/bitnami/postgresql
    networks:
      - cintegre-network
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "pg_isready -U ${POSTGRESQL_USERNAME} -d ${POSTGRESQL_DATABASE}",
        ]
      interval: 5s
      timeout: 5s
      retries: 20

  # Backend (Server)
  server:
    build: ./server
    restart: always
    ports:
      - "${SERVER_PORT}:4000"
    environment:
      - NODE_ENV=${NODE_ENV}
      - DATABASE_URL=${DATABASE_URL}
      - JWT_SECRET=${JWT_SECRET}
      - PORT=${SERVER_PORT}
      - HOST=${HOST}
      - CORS_ORIGIN=${CORS_ORIGIN}
    depends_on:
      db:
        condition: service_healthy
    networks:
      - cintegre-network

  # Frontend (Client)
  client:
    build: ./client
    restart: always
    ports:
      - "${CLIENT_PORT}:3000"
    environment:
      - NODE_ENV=${NODE_ENV}
      - NEXT_PUBLIC_API_URL=${NEXT_PUBLIC_API_URL}
    depends_on:
      - server
    networks:
      - cintegre-network

volumes:
  postgresql_data: {}

networks:
  cintegre-network:
    driver: bridge
