services:
  # Backend (Server)
  server:
    container_name: cintegreserver
    build: ./server
    restart: always
    ports:
      - "${SERVER_PORT}:3003"
    environment:
      - NODE_ENV=${NODE_ENV}
      - DATABASE_URL=${DATABASE_URL}
      - JWT_SECRET=${JWT_SECRET}
      - PORT=${SERVER_PORT}
      - CORS_ORIGIN=${CORS_ORIGIN}
    networks:
      - boraimpactar2

  # Frontend (Client)
  client:
    container_name: cintegreclient
    build:
      context: ./client
      args:
        NEXT_PUBLIC_API_URL: ${NEXT_PUBLIC_API_URL}
    restart: always
    ports:
      - "${CLIENT_PORT}:8003"
    environment:
      - NODE_ENV=${NODE_ENV}
      - NEXT_PUBLIC_API_URL=${NEXT_PUBLIC_API_URL}
      - JWT_SECRET=${JWT_SECRET}
      - INTERNAL_API_URL=${INTERNAL_API_URL}
    depends_on:
      - server
    networks:
      - boraimpactar2

volumes:
  postgresql_data: {}

networks:
  boraimpactar2:
    external: true
