services:
  postgres:
    image: postgres:16
    env_file:
      - ./server/.env
    container_name: postgres_db
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRESQL_USERNAME}
      POSTGRES_PASSWORD: ${POSTGRESQL_PASSWORD}
      POSTGRES_DB: ${POSTGRESQL_DATABASE}
    ports:
      - "${DB_PORT}:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  backend:
    build:
      context: ./server
      dockerfile: Dockerfile
    container_name: backend_app
    restart: always
    ports:
      - "3333:3000" # Externo:Interno (ajuste conforme sua app)
    env_file:
      - ./server/.env
    depends_on:
      - postgres

  frontend:
    build:
      context: ./client
      dockerfile: Dockerfile
    container_name: frontend_app
    restart: always
    ports:
      - "3000:3000" # Porta padrão do next start
    env_file:
      - ./client/.env
    depends_on:
      - backend

volumes:
  postgres_data:
