services:
  postgresql:
    container_name: cinconecta
    image: bitnami/postgresql:latest
    ports:
      - ${DB_PORT}:5432
    environment:
      - POSTGRESQL_USERNAME=${POSTGRESQL_USERNAME}
      - POSTGRESQL_PASSWORD=${POSTGRESQL_PASSWORD}
      - POSTGRESQL_DATABASE=${POSTGRESQL_DATABASE}
    volumes:
      - postgresql_data:/bitnami/postgresql

volumes:
  postgresql_data: {}
